name: Terraform CI

on:
  push:
    

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
    ##setup
    - name: Checkout
      uses: actions/checkout@v3
    
    #aws configure
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      run: terraform fmt --recursive
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform prettify
      run: terraform fmt
    
    - name: Terraform Validate
      run: terraform validate 
    
    - uses: terraform-linters/setup-tflint@v3
      with:
       tflint_version: latest
    
    - name: Show version
      run: tflint_version

    - name: Run TFlint
      run: tflint -f compact


#terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file=environments/prod.tfvars



